FE_region=[0,
        #1. Alaska-Aleutian arc
        "Central Alaska",
        "Southern Alaska",
        "Bering Sea",
        "Komandorsky Islands Region",
        "Near Islands, Aleutian Islands",
        "Rat Islands, Aleutian Islands",
        "Andreanof Islands, Aleutian Islands",
        "Pribilof Islands, Alaska Region",
        "Fox Islands, Aleutian Islands",
        "Unimak Island Region, Alaska",
        "Bristol Bay",
        "Alaska Peninsula",
        "Kodiak Island Region, Alaska",
        "Kenai Peninsula, Alaska",
        "Gulf of Alaska",
        "South of Aleutian Islands",
        "South of Alaska",

        #2. Southeastern Alaska to Washington
        "Southern Yukon Territory, Canada",
        "Southeastern Alaska",
        "Off Coast of Southeastern Alaska",
        "West of Vancouver Island",
        "Haida Gwaii Region",
        "British Columbia, Canada",
        "Alberta, Canada",
        "Vancouver Island, Canada Region",
        "Off Coast of Washington",
        "Near Coast of Washington",
        "Washington-Oregon Border Region",
        "Washington",

        #3. Oregon, California and Nevada
        "Off Coast of Oregon",
        "Near Coast of Oregon",
        "Oregon",
        "Western Idaho",
        "Off Coast of Northern California",
        "Near Coast of Northern California",
        "Northern California",
        "Nevada",
        "Off Coast of California",
        "Central California",
        "California-Nevada Border Region",
        "Southern Nevada",
        "Western Arizona",
        "Southern California",
        "California-Arizona Border Region",
        "California-Baja California Border Region",
        "Western Arizona-Sonora Border Region",

        #4. Baja California and Gulf of California
        "Off Western Coast of Baja California",
        "Baja California, Mexico",
        "Gulf of California",
        "Sonora, Mexico",
        "Off Coast of Central Mexico",
        "Near Coast of Central Mexico",

        #5. Mexico-Guatemala area
        "Revilla Gigedo Islands Region",
        "Off Coast of Jalisco, Mexico",
        "Near Coast of Jalisco, Mexico",
        "Near Coast of Michoacan, Mexico",
        "Michoacan, Mexico",
        "Near Coast of Guerrero, Mexico",
        "Guerrero, Mexico",
        "Oaxaca, Mexico",
        "Chiapas, Mexico",
        "Mexico-Guatemala Border Region",
        "Off Coast of Mexico",
        "Off Coast of Michoacan, Mexico",
        "Off Coast of Guerrero, Mexico",
        "Near Coast of Oaxaca, Mexico",
        "Off Coast of Oaxaca, Mexico",
        "Off Coast of Chiapas, Mexico",
        "Near Coast of Chiapas, Mexico",
        "Guatemala",
        "Near Coast of Guatemala",

        #6. Central America
        "Honduras",
        "El Salvador",
        "Near Coast of Nicaragua",
        "Nicaragua",
        "Off Coast of Central America",
        "Off Coast of Costa Rica",
        "Costa Rica",
        "North of Panama",
        "Panama-Costa Rica Border Region",
        "Panama",
        "Panama-Colombia Border Region",
        "South of Panama",

        #7. Caribbean loop
        "Yucatán Peninsula, Mexico",
        "Cuba Region",
        "Jamaica Region",
        "Haiti Region",
        "Dominican Republic Region",
        "Mona Passage",
        "Puerto Rico Region",
        "Virgin Islands",
        "Leeward Islands",
        "Belize",
        "Caribbean Sea",
        "Windward Islands",
        "Near North Coast of Colombia",
        "Near Coast of Venezuela",
        "Trinidad",
        "Northern Colombia",
        "Lake Maracaibo, Venezuela",
        "Venezuela",

        #8. Andean South America
        "Near West Coast of Colombia",
        "Colombia",
        "Off Coast of Ecuador",
        "Near Coast of Ecuador",
        "Colombia-Ecuador Border Region",
        "Ecuador",
        "Off Coast of Northern Peru",
        "Near Coast of Northern Peru",
        "Peru-Ecuador Border Region",
        "Northern Peru",
        "Peru-Brazil Border Region",
        "Western Brazil",
        "Off Coast of Peru",
        "Near Coast of Peru",
        "Central Peru",
        "Southern Peru",
        "Peru-Bolivia Border Region",
        "Northern Bolivia",
        "Central Bolivia",
        "Off Coast of Northern Chile",
        "Near Coast of Northern Chile",
        "Northern Chile",
        "Chile-Bolivia Border Region",
        "Southern Bolivia",
        "Paraguay",
        "Chile-Argentina Border Region",
        "Jujuy Province, Argentina",
        "Salta Province, Argentina",
        "Catamarca Province, Argentina",
        "Tucuman Province, Argentina",
        "Santiago Del Estero Province, Argentina",
        "Northeastern Argentina",
        "Off Coast of Central Chile",
        "Near Coast of Central Chile",
        "Central Chile",
        "San Juan Province, Argentina",
        "La Rioja Province, Argentina",
        "Mendoza Province, Argentina",
        "San Luis Province, Argentina",
        "Cordoba Province, Argentina",
        "Uruguay",

        #9. Extreme South America
        "Off Coast of Southern Chile",
        "Southern Chile",
        "Southern Chile-Argentina Border Region",
        "Southern Argentina",

        #10. Southern Antilles
        "Tierra Del Fuego",
        "Falkland Islands Region",
        "Drake Passage",
        "Scotia Sea",
        "South Georgia Island Region",
        "South Georgia Rise",
        "South Sandwich Islands Region",
        "South Shetland Islands",
        "Antarctic Peninsula",
        "Southwestern Atlantic Ocean",
        "Weddell Sea",

        #11. New Zealand region
        "Off West Coast of North Island, New Zealand",
        "North Island, New Zealand",
        "Off East Coast of North Island, New Zealand",
        "Off West Coast of South Island, New Zealand",
        "South Island, New Zealand",
        "Cook Strait, New Zealand",
        "Off East Coast of South Island, New Zealand",
        "North of Macquarie Island",
        "Auckland Islands, New Zealand Region",
        "Macquarie Island Region",
        "South of New Zealand",

        #12. Kermadec-Tonga-Samoa Basin area
        "Samoa Islands Region",
        "Samoa Islands",
        "South of Fiji Islands",
        "gap",
        "Tonga Islands",
        "Tonga Islands Region",
        "South of Tonga Islands",
        "North of New Zealand",
        "Kermadec Islands Region",
        "Kermadec Islands, New Zealand",
        "South of Kermadec Islands",

        #13. Fiji Islands area
        "North of Fiji Islands",
        "Fiji Islands Region",
        "Fiji Islands",

        #14. Vanuatu Islands
        "Santa Cruz Islands Region",
        "Santa Cruz Islands",
        "Vanuatu Islands Region",
        "Vanuatu Islands",
        "New Caledonia",
        "Loyalty Islands",
        "Southeast of Loyalty Islands",

        #15. Bismarck and Solomon Islands
        "New Ireland Region, Papua New Guinea",
        "North of Solomon Islands",
        "New Britain Region, Papua New Guinea",
        "Solomon Islands",
        "D'Entrecasteaux Islands Region",
        "South of Solomon Islands",

        #16. New Guinea
        "West Papua Region, Indonesia",
        "Near North Coast of West Papua",
        "Ninigo Islands Region, Papua New Guinea",
        "Admiralty Islands Region, Papua New Guinea",
        "Near North Coast of New Guinea, Papua New Guinea",
        "West Papua, Indonesia",
        "New Guinea, Papua New Guinea",
        "Bismarck Sea",
        "Aru Islands Region, Indonesia",
        "Near South Coast of West Papua",
        "Near South Coast of New Guinea, Papua New Guinea",
        "Eastern New Guinea Region, Papua New Guinea",
        "Arafura Sea",

        #17. Caroline Islands area
        "Western Caroline Islands, Micronesia",
        "South of Mariana Islands",

        #18. Guam to Japan
        "Southeast of Honshu, Japan",
        "Bonin Islands, Japan Region",
        "Volcano Islands, Japan Region",
        "West of Mariana Islands",
        "Mariana Islands Region",
        "Mariana Islands",

        #19. Japan-Kuril Islands-Kamchatka Peninsula
        "Kamchatka Peninsula, Russia",
        "Near East Coast of Kamchatka",
        "Off East Coast of Kamchatka",
        "Northwest of Kuril Islands",
        "Kuril Islands",
        "East of Kuril Islands",
        "Eastern Sea of Japan",
        "Hokkaido, Japan Region",
        "Off Coast of Hokkaido, Japan",
        "Near West Coast of Honshu, Japan",
        "Eastern Honshu, Japan",
        "Near East Coast of Honshu, Japan",
        "Off East Coast of Honshu, Japan",
        "Near South Coast of Honshu, Japan",

        #20. Southwestern Japan and Ryukyu Islands
        "South Korea",
        "Western Honshu, Japan",
        "Near South Coast of Western Honshu",
        "Northwest of Ryukyu Islands",
        "Kyushu, Japan",
        "Shikoku, Japan",
        "Southeast of Shikoku, Japan",
        "Ryukyu Islands, Japan",
        "Southeast of Ryukyu Islands",
        "West of Bonin Islands",
        "Philippine Sea",

        #21. Taiwan area
        "Near Coast of southeastern China",
        "Taiwan Region",
        "Taiwan",
        "Northeast of Taiwan",
        "Southwestern Ryukyu Islands, Japan",
        "Southeast of Taiwan",

        #22. Philippine Islands
        "Philippine Islands Region",
        "Luzon, Philippines",
        "Mindoro, Philippines",
        "Samar, Philippines",
        "Palawan, Philippines",
        "Sulu Sea",
        "Panay, Philippines",
        "Cebu, Philippines",
        "Leyte, Philippines",
        "Negros, Philippines",
        "Sulu Archipelago, Philippines",
        "Mindanao, Philippines",
        "East of Philippine Islands",

        #23. Borneo-Sulawesi
        "Borneo",
        "Celebes Sea",
        "Talaud Islands, Indonesia",
        "North of Halmahera, Indonesia",
        "Minahassa Peninsula, Sulawesi",
        "Northern Molucca Sea",
        "Halmahera, Indonesia",
        "Sulawesi, Indonesia",
        "Southern Molucca Sea",
        "Ceram Sea",
        "Buru, Indonesia",
        "Seram, Indonesia",

        #24. Sunda arc
        "Southwest of Sumatra, Indonesia",
        "Southern Sumatra, Indonesia",
        "Java Sea",
        "Sunda Strait, Indonesia",
        "Java, Indonesia",
        "Bali Sea",
        "Flores Sea",
        "Banda Sea",
        "Tanimbar Islands Region, Indonesia",
        "South of Java, Indonesia",
        "Bali Region, Indonesia",
        "South of Bali, Indonesia",
        "Sumbawa Region, Indonesia",
        "Flores Region, Indonesia",
        "Sumba Region, Indonesia",
        "Savu Sea",
        "Timor Region",
        "Timor Sea",
        "South of Sumbawa, Indonesia",
        "South of Sumba, Indonesia",
        "South of Timor, Indonesia",

        #25. Myanmar and Southeast Asia
        "Myanmar-India Border Region",
        "Myanmar-Bangladesh Border Region",
        "Myanmar",
        "Myanmar-China Border Region",
        "Near South Coast of Myanmar",
        "gap",
        "Hainan Island, China",
        "South China Sea",

        #26. India-Xizang-Sichuan-Yunnan
        "Eastern Kashmir",
        "Kashmir-India Border Region",
        "Kashmir-Xizang Border Region",
        "Western Xizang-India Border Region",
        "Xizang",
        "Sichuan, China",
        "Northern India",
        "Nepal-India Border Region",
        "Nepal",
        "Sikkim, India",
        "Bhutan",
        "Eastern Xizang-India Border Region",
        "Southern India",
        "India-Bangladesh Border Region",
        "Bangladesh",
        "Northeastern India",
        "Yunnan, China",
        "Bay of Bengal",

        #27. Southern Xinjiang to Gansu
        "Kyrgyzstan-Xinjiang Border Region",
        "Southern Xinjiang, China",
        "Gansu, China",
        "Western Nei Mongol, China",
        "Kashmir-Xinjiang Border Region",
        "Qinghai, China",

        #28. Lake Issyk-Kul to Lake Baykal
        "Southwestern Siberia, Russia",
        "Lake Baykal Region, Russia",
        "East of Lake Baykal, Russia",
        "Eastern Kazakhstan",
        "Lake Issyk-Kul region",
        "Kazakhstan-Xinjiang Border Region",
        "Northern Xinjiang, China",
        "Russia-Mongolia Border Region",
        "Mongolia",

        #29. Western Asia
        "Ural Mountains Region, Russia",
        "Western Kazakhstan",
        "Eastern Caucasus",
        "Caspian Sea",
        "Northwestern Uzbekistan",
        "Turkmenistan",
        "Turkmenistan-Iran Border Region",
        "Turkmenistan-Afghanistan Border Region",
        "Turkey-Iran Border Region",
        "Armenia-Azerbaijan-Iran Border Region",
        "Northwestern Iran",
        "Iran-Iraq Border Region",
        "Western Iran",
        "Northern and Central Iran",
        "Northwestern Afghanistan",
        "Southwestern Afghanistan",
        "Eastern Arabian Peninsula",
        "Persian Gulf",
        "Southern Iran",
        "Southwestern Pakistan",
        "Gulf of Oman",
        "Off Coast of Pakistan",

        #30. Middle East-Crimea-Eastern Balkans
        "Ukraine-Moldova-Southwestern Russia Region",
        "Romania",
        "Bulgaria",
        "Black Sea",
        "Crimea Region, Ukraine",
        "Western Caucasus",
        "Greece-Bulgaria Border Region",
        "Greece",
        "Aegean Sea",
        "Turkey",
        "Georgia-Armenia-Turkey Border Region",
        "Southern Greece",
        "Dodecanese Islands, Greece",
        "Crete, Greece",
        "Eastern Mediterranean Sea",
        "Cyprus Region",
        "Dead Sea Region",
        "Jordan-Syria Region",
        "Iraq",

        #31. Western Mediterranean area
        "Portugal",
        "Spain",
        "Pyrenees",
        "Near South Coast of France",
        "Corsica, France",
        "Central Italy",
        "Adriatic Sea",
        "Northwestern Balkan Region",
        "West of Gibraltar",
        "Strait of Gibraltar",
        "Balearic Islands, Spain",
        "Western Mediterranean Sea",
        "Sardinia, Italy",
        "Tyrrhenian Sea",
        "Southern Italy",
        "Albania",
        "Greece-Albania Border Region",
        "Madeira Islands, Portugal Region",
        "Canary Islands, Spain Region",
        "Morocco",
        "Northern Algeria",
        "Tunisia",
        "Sicily, Italy",
        "Ionian Sea",
        "Central Mediterranean Sea",
        "Near Coast of Libya",

        #32. Atlantic Ocean
        "North Atlantic Ocean",
        "Northern Mid-Atlantic Ridge",
        "Azores Islands Region",
        "Azores Islands, Portugal",
        "Central Mid-Atlantic Ridge",
        "North of Ascension Island",
        "Ascension Island Region",
        "South Atlantic Ocean",
        "Southern Mid-Atlantic Ridge",
        "Tristan Da Cunha Region",
        "Bouvet Island Region",
        "Southwest of Africa",
        "Southeastern Atlantic Ocean",

        #33. Indian Ocean
        "Eastern Gulf of Aden",
        "Socotra Region",
        "Arabian Sea",
        "Lakshadweep Region, India",
        "Northeastern Somalia",
        "North Indian Ocean",
        "Carlsberg Ridge",
        "Maldive Islands Region",
        "Laccadive Sea",
        "Sri Lanka",
        "South Indian Ocean",
        "Chagos Archipelago Region",
        "Mauritius-Réunion Region",
        "Southwest Indian Ridge",
        "Mid-Indian Ridge",
        "South of Africa",
        "Prince Edward Islands Region",
        "Crozet Islands Region",
        "Kerguelen Islands Region",
        "Broken Ridge",
        "Southeast Indian Ridge",
        "Southern Kerguelen Plateau",
        "South of Australia",

        #34. Eastern North America
        "Saskatchewan, Canada",
        "Manitoba, Canada",
        "Hudson Bay",
        "Ontario, Canada",
        "Hudson Strait Region, Canada",
        "Northern Québec, Canada",
        "Davis Strait",
        "Labrador, Canada",
        "Labrador Sea",
        "Southern Québec, Canada",
        "Gaspe Peninsula, Canada",
        "Eastern Québec, Canada",
        "Anticosti Island, Canada",
        "New Brunswick, Canada",
        "Nova Scotia, Canada",
        "Prince Edward Island, Canada",
        "Gulf of St. Lawrence",
        "Newfoundland, Canada",
        "Montana",
        "Eastern Idaho",
        "Hebgen Lake Region",
        "Yellowstone Region, Wyoming",
        "Wyoming",
        "North Dakota",
        "South Dakota",
        "Nebraska",
        "Minnesota",
        "Iowa",
        "Wisconsin",
        "Illinois",
        "Michigan",
        "Indiana",
        "Southern Ontario, Canada",
        "Ohio",
        "New York",
        "Pennsylvania",
        "Vermont-New Hampshire Region",
        "Maine",
        "Southern New England",
        "Gulf of Maine",
        "Utah",
        "Colorado",
        "Kansas",
        "Iowa-Missouri Border Region",
        "Missouri-Kansas Border Region",
        "Missouri",
        "Missouri-Arkansas Border Region",
        "Eastern Missouri",
        "New Madrid, Missouri Region",
        "Cape Girardeau, Missouri Region",
        "Southern Illinois",
        "Southern Indiana",
        "Kentucky",
        "West Virginia",
        "Virginia",
        "Chesapeake Bay Region",
        "New Jersey",
        "Eastern Arizona",
        "New Mexico",
        "Texas Panhandle Region",
        "Western Texas",
        "Oklahoma",
        "Central Texas",
        "Arkansas-Oklahoma Border Region",
        "Arkansas",
        "Louisiana-Texas Border Region",
        "Louisiana",
        "Mississippi",
        "Tennessee",
        "Alabama",
        "Western Florida",
        "Georgia, USA",
        "Florida-Georgia Border Region",
        "South Carolina",
        "North Carolina",
        "Off East Coast of United States",
        "Florida Peninsula",
        "Bahama Islands",
        "Eastern Arizona-Sonora Border Region",
        "New Mexico-Chihuahua Border Region",
        "Texas-Mexico Border Region",
        "Southern Texas",
        "Near Coast of Texas",
        "Chihuahua, Mexico",
        "Northern Mexico",
        "Central Mexico",
        "Jalisco, Mexico",
        "Veracruz, Mexico",
        "Gulf of Mexico",
        "Bay of Campeche",

        #35. Eastern South America
        "Brazil",
        "Guyana",
        "Suriname",
        "French Guiana",

        #36. Northwestern Europe
        "Ireland",
        "United Kingdom",
        "North Sea",
        "Southern Norway",
        "Sweden",
        "Baltic Sea",
        "France",
        "Bay of Biscay",
        "The Netherlands",
        "Belgium",
        "Denmark",
        "Germany",
        "Switzerland",
        "Northern Italy",
        "Austria",
        "Czechia and Slovakia",
        "Poland",
        "Hungary",

        #37. Africa
        "gap",
        "Southern Algeria",
        "Libya",
        "Egypt",
        "Red Sea",
        "Western Arabian Peninsula",
        "Chad Region",
        "Sudan",
        "Ethiopia",
        "Western Gulf of Aden",
        "Northwestern Somalia",
        "Off South Coast of Northwest Africa",
        "Cameroon",
        "Equatorial Guinea",
        "Central African Republic",
        "Gabon",
        "Republic of Congo",
        "Democratic Republic of Congo",
        "Uganda",
        "Lake Victoria Region",
        "Kenya",
        "Southern Somalia",
        "Lake Tanganjika Region",
        "Tanzania",
        "Northwest of Madagascar",
        "Angola",
        "Zambia",
        "Malawi",
        "Namibia",
        "Botswana",
        "Zimbabwe",
        "Mozambique",
        "Mozambique Channel",
        "Madagascar",
        "South Africa",
        "Lesotho",
        "Swaziland",
        "Off Coast of South Africa",

        #38. Australia
        "Northwest of Australia",
        "West of Australia",
        "Western Australia",
        "Northern Territory, Australia",
        "South Australia",
        "Gulf of Carpentaria",
        "Queensland, Australia",
        "Coral Sea",
        "Northwest of New Caledonia",
        "Southwest of New Caledonia",
        "Southwest of Australia",
        "Off South Coast of Australia",
        "Near Coast of South Australia",
        "New South Wales, Australia",
        "Victoria, Australia",
        "Near Southeastern Coast of Australia",
        "Near East Coast of Australia",
        "East of Australia",
        "Norfolk Island Region",
        "Northwest of New Zealand",
        "Bass Strait",
        "Tasmania Region, Australia Region",
        "Southeast of Australia",

        #39. Pacific Basin
        "North Pacific Ocean",
        "Hawaiian Islands Region",
        "Hawaii",
        "Eastern Caroline Islands, Micronesia",
        "Marshall Islands Region",
        "Enewetak Atoll Region, Marshall Islands",
        "Bikini Atoll Region, Marshall Islands",
        "Gilbert Islands, Kiribati Region",
        "Johnston Island Region",
        "Line Islands Region, Kiribati",
        "Palmyra Island Region, Kiribati",
        "Kiritimati Region, Kiribati",
        "Tuvalu Region",
        "Phoenix Islands, Kiribati Region",
        "Tokelau Islands Region",
        "Northern Cook Islands",
        "Cook Islands Region",
        "Society Islands Region",
        "Tubuai Islands Region",
        "Marquesas Islands Region",
        "Tuamotu Archipelago Region",
        "South Pacific Ocean",

        #40. Arctic zone
        "Lomonosov Ridge",
        "Arctic Ocean",
        "Near North Coast of Greenland",
        "Eastern Greenland",
        "Iceland Region",
        "Iceland",
        "Jan Mayen Island Region",
        "Greenland Sea",
        "North of Svalbard",
        "Norwegian Sea",
        "Svalbard Region",
        "North of Franz Josef Land",
        "Franz Josef Land, Russia",
        "Northern Norway",
        "Barents Sea",
        "Novaya Zemlya, Russia",
        "Kara Sea",
        "Near Coast of Western Siberia, Russia",
        "North of Severnaya Zemlya",
        "Severnaya Zemlya, Russia",
        "Near Coast of Central Siberia, Russia",
        "East of Severnaya Zemlya, Russia",
        "Laptev Sea",

        #41. Eastern Asia
        "Southeastern Siberia, Russia",
        "Eastern Russia-Northeastern China Border Region",
        "Northeastern China",
        "North Korea",
        "Sea of Japan",
        "Primor'ye, Russia",
        "Sakhalin, Russia",
        "Sea of Okhotsk",
        "Southeastern China",
        "Yellow Sea",
        "Off East Coast of Eastern China",

        #42. Northeastern Asia, Northern Alaska to Greenland
        "North of New Siberian Islands",
        "New Siberian Islands, Russia",
        "East Siberian Sea",
        "Near North Coast of Eastern Siberia",
        "Eastern Siberia, Russia",
        "Chukchi Sea",
        "Bering Strait",
        "St. Lawrence Island, Alaska Region",
        "Beaufort Sea",
        "Northern Alaska",
        "Northern Yukon Territory, Canada",
        "Queen Elizabeth Islands, Canada",
        "Northwest Territories-Nunavut, Canada",
        "Western Greenland",
        "Baffin Bay",
        "Baffin Island Region, Canada",

        #43. Southeastern and Antarctic Pacific Ocean
        "Southeast Central Pacific Ocean",
        "Southern East Pacific Rise",
        "Easter Island Region",
        "West Chile Rise",
        "Juan Fernandez Islands Region",
        "East of North Island, New Zealand",
        "Chatham Islands, New Zealand Region",
        "South of Chatham Islands",
        "Pacific-Antarctic Ridge",
        "Southern Pacific Ocean",

        #44. Galápagos Islands area
        "East Central Pacific Ocean",
        "Central East Pacific Rise",
        "West of Galápagos Islands",
        "Galápagos Islands Region",
        "Galápagos Islands, Ecuador",
        "Southwest of Galápagos Islands",
        "Southeast of Galápagos Islands",

        #45. Macquarie loop
        "South of Tasmania",
        "West of Macquarie Island",
        "Balleny Islands Region",

        #46. Andaman Islands to Sumatra
        "Andaman Islands, India Region",
        "Nicobar Islands, India Region",
        "Off West Coast of Northern Sumatra",
        "Northern Sumatra, Indonesia",
        "Malay Peninsula",
        "Gulf of Thailand",

        #47. Baluchistan
        "Southeastern Afghanistan",
        "Pakistan",
        "Southwestern Kashmir",
        "India-Pakistan Border Region",

        #48. Hindu Kush and Pamir area
        "Central Kazakhstan",
        "Southeastern Uzbekistan",
        "Tajikistan",
        "Kyrgyzstan",
        "Afghanistan-Tajikistan Border Region",
        "Hindu Kush Region, Afghanistan",
        "Tajikistan-Xinjiang Border Region",
        "Northwestern Kashmir",

        #49. Northern Eurasia
        "Finland",
        "Norway-Russia Border Region",
        "Finland-Russia Border Region",
        "Baltic-Belarus-Northwestern Russia Region",
        "Northwestern Siberia, Russia",
        "Northcentral Siberia, Russia",

        #50. Antarctica
        "Victoria Land, Antarctica",
        "Ross Sea",
        "Antarctica",

        "Northern East Pacific Rise", #5. Mexico-Guatemala area
        "North of Honduras", #7. Caribbean loop
        "East of South Sandwich Islands", #10. Southern Antilles
        "Thailand", #25. Myanmar and Southeast Asia
        "Laos", #25. Myanmar and Southeast Asia
        "Cambodia", #25. Myanmar and Southeast Asia
        "Vietnam", #25. Myanmar and Southeast Asia
        "Gulf of Tongking", #25. Myanmar and Southeast Asia
        "Reykjanes Ridge", #32. Atlantic Ocean
        "Azores-Cape St. Vincent Ridge", #32. Atlantic Ocean
        "Owen Fracture Zone Region", #33. Indian Ocean
        "Indian Ocean Triple junction", #33. Indian Ocean
        "Western Indian-Antarctic Ridge", #33. Indian Ocean
        "Western Sahara", #37. Africa
        "Mauritania", #37. Africa
        "Mali", #37. Africa
        "Senegal-Gambia Region", #37. Africa
        "Guinea Region", #37. Africa
        "Sierra Leone", #37. Africa
        "Liberia Region", #37. Africa
        "Côte d'Ivoire", #37. Africa
        "Burkina Faso", #37. Africa
        "Ghana", #37. Africa
        "Benin-Togo Region", #37. Africa
        "Niger", #37. Africa
        "Nigeria", #37. Africa
        "Southeast of Easter Island", #43. Southeastern and Antarctic Pacific Ocean
        "Galápagos Triple Junction Region" #44. Galápagos Islands area
]

print(FE_region[632])
